SET C51INC=D:\Keil_v5\C51\Inc;D:\Keil_v5\C51\Inc\STC
SET C51LIB=D:\Keil_v5\C51\Lib
SET CPU_TYPE=STC15W4K32S4
SET CPU_VENDOR=STC
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x02160EC0
"D:\Keil_v5\C51\BIN\A51.EXE" @".\Objects\STARTUP._ia"
"D:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\led1602.__i"
"D:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\main.__i"
"D:\Keil_v5\C51\BIN\BL51.EXE" @".\Objects\main.lnp"
"D:\Keil_v5\C51\BIN\OH51.EXE" ".\Objects\main" 
